# Use slim Python base
FROM python:3.11-slim

# Set workdir
WORKDIR /app

# Install system deps
RUN apt-get update && apt-get install -y build-essential

# Copy code
COPY . /app

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose port
EXPOSE 8000

# Run with Uvicorn (ASGI)
CMD ["uvicorn", "core.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
