# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'websocket-app'
    static_configs:
      - targets: ['web_blue:8000']
        labels:
          deployment_color: 'blue'
      - targets: ['web_green:8000']
        labels:
          deployment_color: 'green'
    scrape_interval: 30s
    metrics_path: '/metrics/'
    scheme: 'http'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']